# Generated by Django 5.2.14 on 2026-07-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_user_google_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='wallet',
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Debit Card', 'Debit Card'), ('Credit Card', 'Credit Card')], default='Cash', max_length=20),
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
